const saavnDataConfigs = {
  home: {
    heading: 'title',
    title: 'title',
    id: 'id',
    subtitle: 'subtitle',
    images: 'image',
    isExplicit: 'explicit_content',
    type: 'type',
    playCount: 'play_count',
    token: 'perma_url',
    moreInfo: {
      firstName: 'more_info.firstname',
      lastName: 'more_info.lastname',
      artists: 'more_info.artistMap.artists',
      releaseDate: 'more_info.release_date',
      songCount: 'more_info.song_count',
      followers: 'more_info.follower_count',
      description: 'more_info.description',
      releaseYear: 'more_info.release_year',
      editorialLanguage: 'more_info.editorial_language',
      isExplicit: 'more_info.explicit_content',
      stationType: 'more_info.featured_station_type',
      color: 'more_info.color',
      language: 'more_info.language',
      stationDisplayText: 'more_info.station_display_text',
    },
    language: 'language',
  },
  moduleConfig: {
    radio: 'radio.featured_stations',
    newAlbums: 'new_albums',
    charts: 'charts',
    topShows: 'top_shows.shows',
    newTrending: 'new_trending',
    topPlaylists: 'top_playlists',
  },
  albumConfig: {
    id: 'id',
    title: ['title', 'name'],
    subtitle: 'subtitle',
    description: 'header_desc',
    type: 'type',
    token: ['perma_url', 'url'],
    desc: 'description',
    images: 'image',
    language: 'language',
    year: 'year',
    listCount: 'list_count',
    listType: 'list_type',
    list: 'list',
    isExplicit: 'explicit_content',
    copyright: 'more_info.copyright_text',
    songCount: 'more_info.song_count',
    contents: 'more_info.contents',
    followerCount: 'more_info.follower_count',
    fanCount: 'more_info.fan_count',
    editor: 'more_info.firstName',
    artists: 'more_info.artistMap.artists',
    playlistDuration: 'more_info.subtitle_desc.0',
    playlistSongCount: 'more_info.subtitle_desc.1',
  },
  list: {
    id: 'id',
    title: 'title',
    subtitle: 'subtitle',
    images: 'image',
    language: 'language',
    year: 'year',
    type: 'type',
    isExplicit: 'explicit_content',
    playCount: 'play_count',
    music: 'more_info.music',
    album: 'more_info.album',
    albumId: 'more_info.album_id',
    label: 'more_info.label',
    mediaUrls: 'more_info.encrypted_media_url',
    duration: 'more_info.duration',
    copyright: 'more_info.copyright_text',
    release_date: 'more_info.release_date',
    hasLyrics: 'more_info.has_lyrics',
    artists: 'more_info.artistMap.artists',
    origin: 'more_info.origin',
    token: ['more_info.url', 'perma_url', 'url'],
  },
  artistMeta: {
    title: 'name',
    id: ['artistId', 'id'],
    subtitle: 'subtitle',
    images: ['image', 'image_url'],
    followers: 'follower_count',
    type: 'type',
    subtype: 'dominantType',
    bio: 'bio',
    token: ['perma_url', 'url'],
  },
  songDetails: {
    endpoint: 'source',
    heading: 'title',
    artistIds: 'source_params.artist_ids',
    actorIds: 'source_params.actor_ids',
    songId: 'source_params.song_id',
    language: ['source_params.language', 'source_params.entity_language'],
    type: 'source_params.entity_type',
    pid: 'source_params.pid',
  },
  albumReco: {
    endpoint: 'source',
    heading: 'title',
    albumId: 'source_params.albumid',
    language: ['source_params.language', 'source_params.entity_language'],
    type: 'source_params.entity_type',
    year: 'source_params.album_year',
    listId: 'source_params.listid',
  },
};

const gaanaDataConfigs = {
  radio: {
    language: 'language',
    key: 'seokey',
    name: 'name',
    image: 'artwork',
    id: 'entity_id',
    type: 'entity_type',
    favorites: 'favorite_count',
    count: '',
  },
  song: {
    id: 'track_id',
    title: 'track_title',
    subtitle: 'album_title',
    images: 'artwork_large',
    image: 'artwork',
    language: 'language',
    album: 'album_title',
    albumId: 'album_id',
    duration: 'duration',
    releaseDate: 'release_date',
    artists: 'artist',
    key: 'seokey',
    albumKey: 'albumseokey',
    genres: 'gener',
  },
};

const ytmDataConfigs = {
  songConfig: {
    id: 'videoId',
    title: 'title',
    subtitle: 'subtitle',
    images: 'thumbnails.1.url',
    image: 'thumbnails.1.url',
    album: 'album.name',
    albumId: 'album.id',
    artists: 'artists',
    isExplicit: 'isExplicit',
    duration: 'duration',
  },
  albumOrPlaylistConfig: {
    id: 'browseId',
    radioId: 'radioId',
    playlistId: ['audioPlaylistId', 'playlistId'],
    description: 'description',
    title: ['title', 'name'],
    subtitle: 'subtitle',
    type: 'type',
    token: 'perma_url',
    desc: 'description',
    images: 'thumbnails.1.url',
    year: 'year',
    isExplicit: 'isExplicit',
    artist: 'artists',
  },
  contentConfig: {
    id: 'id',
    title: 'title',
    contents: 'contents',
  },
};

export { gaanaDataConfigs, saavnDataConfigs, ytmDataConfigs };
