const saavnDataConfigs = {
  home: {
    heading: 'title',
    title: 'title',
    id: 'id',
    subtitle: 'subtitle',
    images: 'image',
    isExplicit: 'explicit_content',
    type: 'type',
    playCount: 'play_count',
    moreInfo: {
      firstName: 'more_info.firstname',
      lastName: 'more_info.lastname',
      artists: 'more_info.artistMap.artists',
      releaseDate: 'more_info.release_date',
      songCount: 'more_info.song_count',
      followers: 'more_info.follower_count',
      description: 'more_info.description',
      releaseYear: 'more_info.release_year',
      editorialLanguage: 'more_info.editorial_language',
      isExplicit: 'more_info.explicit_content',
      stationType: 'more_info.featured_station_type',
      color: 'more_info.color',
      language: 'more_info.language',
      stationDisplayText: 'more_info.station_display_text',
    },
    language: 'language',
  },
  moduleConfig: {
    radio: 'radio.featured_stations',
    newAlbums: 'new_albums',
    charts: 'charts',
    topShows: 'top_shows.shows',
    newTrending: 'new_trending',
    topPlaylists: 'top_playlists',
  },
  albumConfig: {
    id: 'id',
    description: 'header_desc',
    title: 'title',
    subtitle: 'subtitle',
    type: 'type',
    images: 'image',
    language: 'language',
    year: 'year',
    copyright: 'more_info.copyright_text',
    songCount: 'more_info.song_count',
    listCount: 'list_count',
    listType: 'list_type',
    list: 'list',
  },
  list: {
    id: 'id',
    title: 'title',
    subtitle: 'subtitle',
    images: 'image',
    language: 'language',
    year: 'year',
    isExplicit: 'explicit_content',
    playCount: 'play_count',
    music: 'more_info.music',
    album: 'more_info.album',
    albumId: 'more_info.album_id',
    label: 'more_info.label',
    mediaUrls: 'more_info.encrypted_media_url',
    duration: 'more_info.duration',
    copyright: 'more_info.copyright_text',
    release_date: 'more_info.release_date',
    hasLyrics: 'more_info.has_lyrics',
    artists: 'more_info.artistMap.primary_artists',
  },
};

export { saavnDataConfigs };
